apiVersion: v1
kind: DaemonSet
metadata:
  name: wg-gateway
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: wg-gateway
  template:
    metadata:
      labels:
        app: wg-gateway
      spec:
        nodeSelector:
          kubernetes.io/hostname: control-plane
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: "Exists"
            effect: "NoSchedule"
        hostNetwork: true
        containers:
          - name: nftables
            image: my-registry/my-image
            securityContext: privileged

